import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { LoadingScreen } from "@/components/LoadingScreen";
import { Toaster } from "@/components/ui/toaster"
import { Providers } from './providers'
import { SvgCursor } from './CustomCursor'
import { headers } from "next/headers"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PPID Kota Surakarta",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-ppid.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = headers().get('x-pathname') || '';

  const isAdminRoute = pathname.startsWith('/admin');

  console.log(pathname)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isAdminRoute ? (
          <>
            <LoadingScreen />
            <Toaster />
            <SvgCursor />
            <Providers>{children}</Providers>
          </>
        ) : (
          <>
            <Navbar />
            <LoadingScreen />
            <Toaster />
            <SvgCursor />
            <Providers>{children}</Providers>
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
