export const dataDipKota = {
    items: [
        {
            no: "1",
            title: "Kedudukan/Domisili beserta alamat lengkap",
            summary:
                "Berisi tentang kedudukan, domisili, alamat lengkap Pemerintah Provinsi DKI Jakarta",
            informationOfficer: "PPID Provinsi",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Hard & Soft (File_pdf)",
            retentionPeriod: "Selama Berlaku",
            mediaType: "https://jakarta.go.id/kantor-pemerintah-provinsi",
        },
        {
            no: "2",
            title: "Visi dan Misi",
            summary:
                "Memuat informasi mengenai Visi dan Misi Pemerintah Provinsi DKI Jakarta",
            informationOfficer: "PPID Provinsi",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Hard & Soft (File_pdf)",
            retentionPeriod: "Selama Berlaku",
            mediaType: "https://jakarta.go.id/visi-misi",
        },
        {
            no: "3",
            title: "Struktur Organisasi",
            summary:
                "Struktur organisasi Pemerintah Provinsi DKI Jakarta beserta unit kerja",
            informationOfficer: "Biro Organisasi",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Hard & Soft (File_pdf)",
            retentionPeriod: "5 Tahun",
            mediaType: "https://jakarta.go.id/struktur-organisasi",
        },
        {
            no: "4",
            title: "Daftar Pejabat Struktural",
            summary:
                "Daftar pejabat eselon di lingkungan Pemerintah Provinsi DKI Jakarta",
            informationOfficer: "Biro Kepegawaian",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Soft (File_xlsx)",
            retentionPeriod: "1 Tahun",
            mediaType: "https://jakarta.go.id/daftar-pejabat",
        },
        {
            no: "5",
            title: "Profil Pimpinan",
            summary: "Profil Gubernur, Wakil Gubernur, dan pimpinan lainnya",
            informationOfficer: "Biro Kepala Daerah",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Hard & Soft (File_pdf)",
            retentionPeriod: "Selama Menjabat",
            mediaType: "https://jakarta.go.id/profil-pimpinan",
        },
        {
            no: "6",
            title: "Tugas dan Fungsi",
            summary: "Tugas pokok dan fungsi unit kerja Pemprov DKI Jakarta",
            informationOfficer: "Masing-masing Unit Kerja",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Hard & Soft (File_pdf)",
            retentionPeriod: "5 Tahun",
            mediaType: "https://jakarta.go.id/tugas-fungsi",
        },
        {
            no: "7",
            title: "Peraturan Daerah",
            summary: "Kumpulan Perda Provinsi DKI Jakarta",
            informationOfficer: "Biro Hukum",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Soft (File_pdf)",
            retentionPeriod: "Permanen",
            mediaType: "https://jakarta.go.id/peraturan-daerah",
        },
        {
            no: "8",
            title: "Laporan Kinerja",
            summary: "Laporan Kinerja Instansi Pemerintah (LKIP) Pemprov DKI Jakarta",
            informationOfficer: "Biro Pembangunan",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Soft (File_pdf)",
            retentionPeriod: "5 Tahun",
            mediaType: "https://jakarta.go.id/laporan-kinerja",
        },
        {
            no: "9",
            title: "Laporan Keuangan",
            summary: "Laporan Keuangan Pemerintah Daerah (LKPD) Pemprov DKI Jakarta",
            informationOfficer: "Biro Keuangan",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Soft (File_pdf)",
            retentionPeriod: "5 Tahun",
            mediaType: "https://jakarta.go.id/laporan-keuangan",
        },
        {
            no: "10",
            title: "Rencana Pembangunan",
            summary: "Dokumen perencanaan pembangunan daerah",
            informationOfficer: "Biro Pembangunan",
            responsibleOfficer: "PPID Provinsi",
            creationTime: "Tahun 2025, Jakarta",
            availableForm: "Soft (File_pdf)",
            retentionPeriod: "5 Tahun",
            mediaType: "https://jakarta.go.id/rencana-pembangunan",
        },
    ],
};
